# Generated by Django 5.0.2 on 2024-04-02 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STREAMING', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelis',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pelis',
            name='poster',
            field=models.ImageField(null=True, upload_to='posters/'),
        ),
    ]
