# Generated by Django 5.0.2 on 2024-04-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STREAMING', '0003_remove_pelis_mostrar_alter_pelis_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelis',
            name='mostrar',
            field=models.BooleanField(default=True),
        ),
    ]
